"""
Rule-based chatbot. No external API, no model download — every answer
is generated by pattern-matching the user's question against a small
set of intents and pulling the answer from the live app state.

The bot is intentionally small but useful. Recognised intents:

  * "what is X" / "explain X"  -> glossary lookup (SMMA, ETQ, LTQ, ...)
  * "show Y" / "price Y" / "LTP Y" -> pulls LTP, SMMA(20), SMMA(120)
                                       for a Nifty 100 symbol
  * "top movers" / "best X"     -> ranks the universe by SMMA gap or
                                    LTQ acceleration
  * "open positions" / "my trades" -> lists currently-open trades
  * "help" / "what can you do"  -> returns a usage tip list
  * anything else               -> fuzzy match against the FAQ, or
                                    "I don't know" if nothing matches

The bot has no memory across turns — each call is stateless. That's
fine for a screener assistant and avoids building a session store.
"""

import re
import difflib
from datetime import datetime
from typing import Optional

import websocket_client as wsc
from shared import signals, open_trades_snapshot


# ---------------------------------------------------------------------------
# Glossary — answers to "what is X" / "explain X"
# ---------------------------------------------------------------------------
GLOSSARY = {
    "smma":   "SMMA (Smoothed Moving Average) is an EMA with a long warm-up. "
              "We use SMMA(20) as the fast line and SMMA(120) as the slow line.",
    "etq":    "ETQ (Equal-Traded Quantity) is total shares traded over a "
              "rolling time window — 5, 20, and 60 minutes here.",
    "ltq":    "LTQ (Last Traded Quantity) is the size of the most recent "
              "individual print. A spike in LTQ often precedes a move.",
    "ltp":    "LTP (Last Traded Price) is the most recent traded price for "
              "the symbol.",
    "bid":    "The bid is the best buy price currently quoted in the order book.",
    "ask":    "The ask (or offer) is the best sell price currently quoted.",
    "spread": "Spread is the ask price minus the bid price. A tighter spread "
              "means more liquid.",
    "crossover": "A crossover happens when SMMA(20) crosses SMMA(120). "
                 "Up = BUY signal, down = SELL signal.",
    "rsi":    "RSI (Relative Strength Index) is not used in this app — we "
              "trade pure SMMA crossovers with an AI filter.",
    "volatility": "Volatility here is the standard deviation of the last ~100 "
                  "LTP prints. Higher = more chaotic price action.",
    "pnl":    "P&L (Profit and Loss) for a round-trip trade. For a BUY: "
              "exit_price - entry_price. For a SELL: entry_price - exit_price.",
    "ai filter": "The AI filter is a LogisticRegression trained on your own "
                 "closed trades. It scores each fresh crossover and labels "
                 "it ACCEPT or AVOID.",
}


# ---------------------------------------------------------------------------
# FAQs — short Q&A pairs used by the fuzzy matcher
# ---------------------------------------------------------------------------
FAQS = [
    ("how do signals work",
     "Each tick updates SMMA(20) and SMMA(120). When the fast line crosses "
     "the slow line, that's a signal. Up cross = BUY, down cross = SELL. "
     "Every signal is also sent through the AI filter, which says ACCEPT or AVOID."),
    ("how do i train the model",
     "Let the dashboard run until you have at least 20 closed round-trips in "
     "trade_log.csv, then go to the ML Stats page and click Retrain Now. "
     "Or run `python train_model.py` from the command line."),
    ("how do i export trades",
     "Closed trades live in trade_log.csv at the project root. It's a regular "
     "CSV — open it in Excel, load it in pandas, or stream it from another script."),
    ("what is the auto trade toggle",
     "Auto-trade is currently a stub. When ON, every ACCEPT-ed signal pushes "
     "an AUTO_TRADE_STUB alert onto the bus so you can see what would have "
     "been traded. No real order is placed — you'd need to wire that up "
     "yourself with your broker's order API."),
    ("how do i change smma periods",
     "Open the Settings page. The SMMA fast and slow periods are bound to "
     "live Tk Variables; changes apply on the next refresh tick."),
    ("why is the dashboard empty",
     "Either the liquidity filter (1,000,000 bid and ask qty) is filtering "
     "out everything, or the feed hasn't had time to warm up. Try Use Mock "
     "Feed from the Login page to test the UI with synthetic data."),
    ("what does accept mean",
     "The AI filter saw the entry-time features and predicted P(profitable) "
     ">= 0.5. AVOID means < 0.5. The model is retrained on your own trades, "
     "so what ACCEPT means depends on your own historical win rate."),
    ("can i backtest",
     "Not yet. The trade log is a forward-only record. To backtest, replay "
     "historical ticks through SymbolState and run the same crossover logic — "
     "the code in indicators.py and dashboard_page.py is already structured "
     "to make that feasible."),
]


# ---------------------------------------------------------------------------
# Intent matchers
# ---------------------------------------------------------------------------
_SYMBOL_PATTERN = r"\b([A-Z][A-Z0-9&\-]{2,15})\b"  # RELIANCE, M&M, BAJAJ-AUTO, etc.
_VALID_SYMBOLS = set(wsc.NIFTY_100_SYMBOLS)


def _norm(text: str) -> str:
    return re.sub(r"\s+", " ", text.strip().lower())


def _find_symbol(text: str) -> Optional[str]:
    """Return the Nifty 100 symbol mentioned in the text, if any.

    Match case-insensitively so 'price reliance' and 'Price RELIANCE'
    both work, but only accept the candidate if it's a real Nifty 100
    symbol — this prevents common English words (e.g. 'top', 'ltp')
    from being mistaken for tickers.
    """
    for m in re.finditer(_SYMBOL_PATTERN, text, re.IGNORECASE):
        candidate = m.group(1).upper()
        if candidate in _VALID_SYMBOLS:
            return candidate
    return None


def _glossary(term: str) -> Optional[str]:
    term = term.lower().strip()
    if term in GLOSSARY:
        return GLOSSARY[term]
    # Fuzzy match against keys so "smma 20" still finds "smma".
    keys = list(GLOSSARY.keys())
    matches = difflib.get_close_matches(term, keys, n=1, cutoff=0.6)
    if matches:
        return GLOSSARY[matches[0]]
    return None


def _fuzzy_faq(question: str) -> Optional[str]:
    q = _norm(question)
    if not q:
        return None
    questions = [f[0] for f in FAQS]
    matches = difflib.get_close_matches(q, questions, n=1, cutoff=0.55)
    if not matches:
        return None
    for stored_q, answer in FAQS:
        if stored_q == matches[0]:
            return answer
    return None


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------

HELP_TEXT = (
    "I can help with:\n"
    "  • Definitions — try 'what is smma' or 'explain etq'\n"
    "  • Symbol lookup — 'price reliance', 'ltp tcs', 'show infosys'\n"
    "  • Top movers — 'top 5 by smma gap', 'best by ltq acceleration'\n"
    "  • Your open positions — 'open trades', 'my positions'\n"
    "  • Recent signals — 'recent signals', 'latest crossovers'\n"
    "  • General help — 'help'"
)


def _format_symbol_state(sym: str) -> str:
    st = wsc.states.get(sym)
    if st is None or st.ltp == 0:
        return f"I don't have any data for {sym} yet. The feed may still be warming up."
    parts = [f"{sym}  LTP ₹{st.ltp:.2f}"]
    if st.smma20:
        parts.append(f"  SMMA20 ₹{st.smma20:.2f}")
    if st.smma120:
        parts.append(f"  SMMA120 ₹{st.smma120:.2f}")
    if st.bid_qty:
        parts.append(f"\nBid ₹{st.bid_price:.2f} × {st.bid_qty:,}    "
                     f"Ask ₹{st.ask_price:.2f} × {st.ask_qty:,}")
    parts.append(f"\nETQ 5m={st.get_etq(5):,}  20m={st.get_etq(20):,}  60m={st.get_etq(60):,}")
    return "".join(parts)


def _format_open_positions() -> str:
    opens = open_trades_snapshot()
    if not opens:
        return "You have no open positions right now."
    lines = [f"Open positions ({len(opens)}):"]
    for sym, t in opens.items():
        lines.append(
            f"  • {sym:12} {t['direction']:4} entry ₹{t['entry_price']:.2f}  "
            f"@ {t['entry_time'].strftime('%H:%M:%S')}"
        )
    return "\n".join(lines)


def _format_recent_signals(n: int = 5) -> str:
    recs = signals.all()[-n:]
    if not recs:
        return "No crossovers have fired yet."
    lines = [f"Recent {len(recs)} crossovers:"]
    for r in reversed(recs):
        lines.append(
            f"  • {r.when.strftime('%H:%M:%S')}  {r.symbol:12} {r.direction:4} "
            f"LTP ₹{r.ltp:.2f}  {r.decision} (p={r.probability:.2f})"
        )
    return "\n".join(lines)


def _rank_by_something(rank_key: str, top_n: int = 5) -> str:
    """Sort the universe by `rank_key` and return the top N."""
    rows = []
    for sym, st in wsc.states.items():
        if st.ltp == 0 or not st.smma20 or not st.smma120:
            continue
        f = st.get_features()
        if rank_key == "smma_gap":
            score = f["smma_gap_pct"]
            label = "SMMA gap %"
        elif rank_key == "ltq_accel":
            score = f["ltq_ratio_2m_5m"]
            label = "LTQ 2m/5m ratio"
        elif rank_key == "imbalance":
            score = f["bid_ask_imbalance"]
            label = "bid-ask imbalance"
        else:
            return f"Unknown ranking: {rank_key}"
        rows.append((score, sym, st.ltp))
    if not rows:
        return "Not enough data yet to rank."
    rows.sort(key=lambda r: r[0], reverse=True)
    lines = [f"Top {min(top_n, len(rows))} by {label}:"]
    for score, sym, ltp in rows[:top_n]:
        lines.append(f"  • {sym:12} {score:+.4f}   LTP ₹{ltp:.2f}")
    return "\n".join(lines)


def _parse_top_n(text: str, default: int = 5) -> int:
    m = re.search(r"\b(?:top\s+)?(\d{1,2})\b", text)
    if m:
        n = int(m.group(1))
        return max(1, min(20, n))
    return default


def respond(question: str) -> str:
    """
    Main entry point. Takes the raw user question and returns a string
    answer. Pure function — no Tk dependency, easy to unit-test.
    """
    q = _norm(question)
    if not q:
        return "Type a question or 'help' to see what I can do."

    # Help
    if q in ("help", "?", "what can you do", "commands"):
        return HELP_TEXT

    # Recent signals
    if any(k in q for k in ("recent signal", "latest signal", "latest cross", "recent cross")):
        return _format_recent_signals(_parse_top_n(q, default=5))

    # Open positions
    if any(k in q for k in ("open position", "open trade", "my position", "my trade", "position")):
        return _format_open_positions()

    # Top rankings
    if any(k in q for k in ("top", "best", "rank", "mover", "biggest")):
        if "imbalance" in q or "bid" in q or "ask" in q:
            return _rank_by_something("imbalance", _parse_top_n(q))
        if "ltq" in q:
            return _rank_by_something("ltq_accel", _parse_top_n(q))
        if "smma" in q or "gap" in q:
            return _rank_by_something("smma_gap", _parse_top_n(q))
        # default: SMMA gap
        return _rank_by_something("smma_gap", _parse_top_n(q))

    # Symbol lookup
    sym = _find_symbol(question)
    if sym is not None and any(k in q for k in (
        "show", "price", "ltp", "quote", "tell me about", "what about", "how is", "status",
    )):
        return _format_symbol_state(sym)

    # Glossary: "what is X" / "explain X" / "define X"
    for prefix in ("what is ", "what's ", "explain ", "define ", "meaning of ", "meaning "):
        if q.startswith(prefix):
            term = q[len(prefix):].strip(" ?.,")
            ans = _glossary(term)
            if ans:
                return ans
            return f"I don't have a definition for '{term}'. Try 'help' for what I can do."

    # "X meaning" or just "X" — try glossary directly
    if sym is None:
        # maybe they typed just a term like "smma" or "etq"
        direct = _glossary(q)
        if direct:
            return direct
        # Single-word question about a known glossary term with no prefix
        for key in GLOSSARY:
            if key in q.split():
                return GLOSSARY[key]

    # Last resort: fuzzy FAQ match
    faq = _fuzzy_faq(q)
    if faq:
        return faq

    return (
        "I'm not sure how to answer that. Try:\n"
        "  • 'help' to see what I can do\n"
        "  • 'price RELIANCE' for a symbol quote\n"
        "  • 'top 5 by smma gap' for the leaderboard\n"
        "  • 'open positions' for your current trades"
    )
